/** Dung 256 tu. Doi so luong la lech phan bo cua derivePassword. */
export const WORDS = [
  "mua","nang","gio","may","suong","trang","sao","troi","bien","song",
  "suoi","ho","thac","nui","doi","rung","cay","la","hoa","co",
  "sen","cuc","dao","mai","tre","truc","thong","lieu","bang","phuong",
  "chim","en","hac","ca","buom","ong","kien","meo","cho","nai",
  "huou","ngua","trau","de","tho","soc","chuot","ran","rua","ben",
  "do","thuyen","neo","cang","cau","pha","bo","duong","ngo","hem",
  "pho","lang","xom","quan","tiem","sap","nha","cua","san","hien",
  "tuong","cot","keo","them","vach","ban","ghe","giuong","tu","ke",
  "hom","ruong","thung","chum","den","nen","dau","lua","tro","than",
  "khoi","hoi","kho","am","giay","muc","but","sach","vo","dong",
  "chu","van","tranh","anh","khung","gam","net","mau","son","cham",
  "khac","in","com","chao","banh","xoi","che","bun","mien","hu",
  "tieu","muoi","ot","gung","toi","hanh","rau","dua","tra","sua",
  "nuoc","ruou","bia","da","kem","chanh","cam","sang","trua","chieu",
  "dem","khuya","rang","hoang","thu","xuan","he","tet","ram","mung",
  "hen","gap","xa","gan","trong","ngoai","tren","duoi","truoc","sau",
  "giua","canh","vui","buon","nho","thuong","yeu","men","quy","tin",
  "tha","lanh","mat","nong","uot","mem","cung","nhe","cao","thap",
  "dai","ngan","rong","hep","day","mong","to","xanh","vang","tim",
  "nau","xam","hong","bac","ngoc","im","reo","ru","hat","cuoi",
  "khoc","buoc","chay","di","ve","qua","xuong","len","ra","vao",
  "dung","ngoi","nam","cui","nga","quay","xoay","mo","khoa","cai",
  "coi","go","dap","vuot","nhin","ngam","doc","viet","noi","nghe",
  "biet","hieu","quen","tinh","thuc","ngu","thay","con","het","voi",
  "khong","mot","hai","ba","bon","bay","tam","chin","moi","cu",
  "bot","dan","bong","chot","luon","hoai",
] as const;
